### ISSUE TITLE
This is close to what I'm looking for

### ISSUE THREAD

**Issue by znmeb** [AntonErtl/fforth#1]
I've been looking for a Forth that I can use on embedded micro-controllers for real-time audio applications. My ideal Forth would be:

1. Uses the Arduino toolchain. All of my micro-controllers can be programmed / debugged via the Arduino IDE.
2. Uses the GForth / vmgen efficient interpreter engine - I want C for portability rather than having to port the core internals to variants of ARM assembly or other IoT boards that aren't ARM.

I've looked at trying to get GForth-ec to cross-compile for a micro-controller but it doesn't seem to work for ARM architectures. Even if it did, that still leaves the problem of making `.hex` or `.uf2` binaries to flash to the boards.

**Comment by AntonErtl** [comment]
I am not familiar with the Arduino toolchain, but the plan for fforth is to use assembly language and self-bootstrapping, with Gforth for the initial bootstrapping on a platform.  No vmgen, because portability (what vmgen provides) is not a goal for fforth, and because vmgen would mean that the user has to understand more than when writing some primitives in assembly language.

Concerning Gforth-EC, I know too little about that to give advice.  You could try asking on gforth at gnu.org (the current Gforth mailing list).

Concerning fforth, don't hold your breath.  Other things occupy me, so I don't find time to develop it.

**Comment by znmeb** [comment]
Thanks! I'll probably write a straightforward Forth in assembly with either direct or subroutine threading. The only really difficult case is the Raspberry Pi Pico. the CPU does not have full 32-bit to 64-bit multiply.
